### ISSUE TITLE
docker-compose up command returns error because of problem in docker-compose.yml file

### ISSUE THREAD

**Issue by eduoliveira85** [Ferrmolina/WordPress-Docker-SASS#1]
I've changed absolutely nothing in the files within, but at $docker-composer up -d I get this response: 

_ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.db.ports is invalid: Invalid port "wp.local:3306:3306", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.wp.ports is invalid: Invalid port "wp.local:80:80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]_

Later then, following [this response](https://stackoverflow.com/a/34457942/10216900) on Stack, I've tried wrapping the ports with double quotes but the problem still happen. 
Am I doing it wrong?

**Comment by Ferrmolina** [comment]
Hello @edueter 

I just pushed a change, fixing what you report.

Thanks.
